import { test, expect } from './fixtures';

test('administrator creates a service with categories and reads the persisted catalog', async ({ page }, testInfo) => {
  await page.goto('/login');
  await page.getByLabel('Employee code', { exact: true }).fill('EMP001');
  await page.getByLabel('Password', { exact: true }).fill(process.env.BIZFLOW_E2E_PASSWORD!);
  await page.getByLabel('Workspace key', { exact: true }).fill(process.env.BIZFLOW_E2E_ADMIN_KEY!);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('link', { name: 'Settings', exact: true }).click();
  await page.getByRole('link', { name: 'Service catalog', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Service catalog', exact: true })).toBeVisible();
  await page.getByLabel('Service name or code', { exact: true }).fill('Template service');
  await page.getByRole('button', { name: 'Apply filters', exact: true }).click();
  await expect(page.getByRole('navigation', { name: 'Service pages' })).toContainText('26 services');
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await expect(page.getByRole('row').filter({ hasText: 'Template service 26' })).toContainText('Inactive');
  await page.getByLabel('Service status', { exact: true }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Apply filters', exact: true }).click();
  await expect(page.getByRole('navigation', { name: 'Service pages' })).toContainText('25 services');
  const code = `SUPPORT-${testInfo.project.name}`;
  const name = `Service support ${testInfo.project.name}`;
  await page.getByLabel('New service code', { exact: true }).fill(code);
  await page.getByLabel('New service name', { exact: true }).fill(name);
  await page.getByLabel('Description', { exact: true }).fill('<script>literal plain text</script>');
  await page.getByRole('button', { name: 'Add category', exact: true }).click();
  await page.getByLabel('Category 1 code', { exact: true }).fill('DEVICE');
  await page.getByLabel('Category 1 name', { exact: true }).fill('Device support');
  await page.getByRole('button', { name: 'Add category', exact: true }).click();
  await page.getByLabel('Category 2 code', { exact: true }).fill('PHONE');
  await page.getByLabel('Category 2 name', { exact: true }).fill('Phone support');
  await page.getByRole('checkbox', { name: 'Category 2 active', exact: true }).uncheck();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('heading', { name: 'Create service', exact: true }).scrollIntoViewIfNeeded();
  await page.locator('section.creation').screenshot({ path: testInfo.outputPath('service-create.png'), animations: 'disabled' });
  await page.getByRole('button', { name: 'Create service', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Service created:' })).toContainText(code);
  await page.getByText('Details', { exact: true }).click();
  await expect(page.getByRole('table')).toContainText('PHONE — Phone support · Inactive');
  await expect(page.getByRole('table')).toContainText('<script>literal plain text</script>');
  await expect(page.locator('table script')).toHaveCount(0);
  await expect(page.getByRole('table')).toContainText('Workflow version: Not configured');
  await page.getByRole('button', { name: `Add category to ${code}`, exact: true }).click();
  await page.getByLabel('Category code', { exact: true }).fill('PHONE');
  await page.getByLabel('Category name', { exact: true }).fill('Later category');
  await page.getByRole('button', { name: 'Save category', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('already exists in the service');
  await expect(page.getByLabel('Category code', { exact: true })).toHaveValue('PHONE');
  await page.getByLabel('Category code', { exact: true }).fill('LATER');
  await page.locator('section.category-editor').screenshot({ path: testInfo.outputPath('service-category.png'), animations: 'disabled' });
  await page.getByRole('button', { name: 'Save category', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Category added:' })).toContainText(`LATER to ${code}`);
  await expect(page.getByRole('table')).toContainText('LATER');
  await expect(page.getByRole('table')).toContainText('PHONE');
  await page.getByRole('button', { name: `Edit service ${code}`, exact: true }).click();
  const editedCode = `UPDATED-${testInfo.project.name}`;
  const editedName = `Updated service ${testInfo.project.name}`;
  await page.getByLabel('Service code', { exact: true }).fill(editedCode);
  await page.getByLabel('Service name', { exact: true }).fill(editedName);
  await page.getByLabel('Service description', { exact: true }).fill('Updated plain text');
  await page.getByRole('checkbox', { name: 'Edited service active', exact: true }).uncheck();
  await page.locator('section.metadata-editor').screenshot({ path: testInfo.outputPath('service-update.png'), animations: 'disabled' });
  await page.getByRole('button', { name: 'Save service', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Service updated:' })).toContainText(editedCode);
  await page.getByText('Details', { exact: true }).click();
  await expect(page.getByRole('table')).toContainText('Updated plain text');
  await expect(page.getByRole('row').filter({ hasText: editedName }).getByRole('cell').last()).toHaveText('Inactive');
  await expect(page.getByRole('table')).toContainText('LATER');
  await expect(page.getByRole('table')).toContainText('PHONE');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: testInfo.outputPath('service-catalog.png'), fullPage: true, animations: 'disabled' });
  await page.getByRole('link', { name: 'Workspace', exact: true }).click();
  await page.getByRole('link', { name: 'Browse service catalog', exact: true }).click();
  await page.getByLabel('Service name or code', { exact: true }).fill(editedCode);
  await page.getByRole('button', { name: 'Apply filters', exact: true }).click();
  await expect(page.getByRole('row').filter({ hasText: editedName })).toBeVisible();
  await expect(page.getByRole('row').filter({ hasText: editedName }).getByRole('cell').last()).toHaveText('Inactive');
  await page.getByText('Details', { exact: true }).click();
  await expect(page.getByRole('table')).toContainText('LATER');
  await expect(page.getByRole('table')).toContainText('Later category');
});

test('employee reads only its workspace service catalog without creation controls', async ({ page }) => {
  await page.goto('/login');
  await page.getByLabel('Employee code', { exact: true }).fill('EMP001');
  await page.getByLabel('Password', { exact: true }).fill(process.env.BIZFLOW_E2E_PASSWORD!);
  await page.getByLabel('Workspace key', { exact: true }).fill(process.env.BIZFLOW_E2E_TENANT_KEY!);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('link', { name: 'Browse service catalog', exact: true }).click();
  await expect(page.getByRole('table')).toContainText('Reader service');
  await expect(page.getByRole('table')).not.toContainText('Template service');
  await page.getByText('Details', { exact: true }).click();
  await expect(page.getByRole('table')).toContainText('Reader category');
  await expect(page.getByRole('button', { name: 'Create service', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Add category to READER', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Edit service READER', exact: true })).toHaveCount(0);
  await page.getByLabel('Service name or code', { exact: true }).fill('No such service');
  await page.getByRole('button', { name: 'Apply filters', exact: true }).click();
  await expect(page.getByText('No services match these filters.', { exact: true })).toBeVisible();
});
