import { test, expect } from './fixtures';

test('administrator pages, filters and creates a named SLA draft through Settings', async ({ page }, testInfo) => {
  await page.goto('/login');
  await page.getByLabel('Employee code', { exact: true }).fill('EMP001');
  await page.getByLabel('Password', { exact: true }).fill(process.env.BIZFLOW_E2E_PASSWORD!);
  await page.getByLabel('Workspace key', { exact: true }).fill(process.env.BIZFLOW_E2E_ADMIN_KEY!);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('link', { name: 'Settings', exact: true }).click();
  await page.getByRole('link', { name: 'SLA profiles', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'SLA profiles', exact: true })).toBeVisible();
  await page.getByLabel('Profile name', { exact: true }).fill('Template SLA');
  await page.getByRole('button', { name: 'Apply filters', exact: true }).click();
  await expect(page.getByRole('navigation', { name: 'SLA profile pages' })).toContainText('26 profiles');
  await expect(page.getByRole('rowheader', { name: /Other tenant/ })).toHaveCount(0);
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await expect(page.getByRole('rowheader', { name: 'Template SLA 26', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Template SLA 26', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'SLA version history', exact: true })).toBeVisible();
  await expect(page.getByRole('navigation', { name: 'SLA version pages' })).toContainText('26 versions');
  await expect(page.getByRole('button', { name: 'Inspect version 26', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('sla-version-history.png'), fullPage: true });
  await page.getByRole('button', { name: 'Inspect version 26', exact: true }).click();
  const detail = page.getByRole('dialog');
  await expect(detail).toContainText('Frozen business calendar');
  await expect(detail).toContainText('08:00–17:30');
  await expect(detail).toContainText('2026-10-03');
  await expect(detail).toContainText('No escalation configured.');
  await expect(page.locator('.mat-mdc-dialog-inner-container')).toHaveCSS('opacity', '1');
  await page.screenshot({ path: testInfo.outputPath('sla-version-detail.png'), animations: 'disabled' });
  await detail.getByText('No escalation configured.', { exact: true }).scrollIntoViewIfNeeded();
  await expect(detail.getByText('No escalation configured.', { exact: true })).toBeInViewport({ ratio: 1 });
  await expect(detail.getByRole('button', { name: 'Close details', exact: true })).toBeInViewport({ ratio: 1 });
  await page.screenshot({ path: testInfo.outputPath('sla-version-detail-end.png'), animations: 'disabled' });
  await detail.getByRole('button', { name: 'Close details', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Inspect version 26', exact: true })).toBeFocused();
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Inspect version 1', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Next', exact: true })).toBeDisabled();
  await page.getByRole('link', { name: 'SLA profiles', exact: true }).click();
  await page.getByLabel('Profile status', { exact: true }).click();
  await page.getByRole('option', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Apply filters', exact: true }).click();
  await expect(page.getByText('No SLA profiles match these filters.', { exact: true })).toBeVisible();
  const name = `Support response ${testInfo.project.name}`;
  await page.getByLabel('New profile name', { exact: true }).fill(name);
  await page.getByRole('button', { name: 'Create draft profile', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Draft profile created:' })).toContainText(name);
  await expect(page.getByRole('rowheader', { name, exact: true })).toBeVisible();
  await expect(page.getByRole('row').filter({ hasText: name })).toContainText('Draft');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: testInfo.outputPath('sla-profile-catalog.png'), fullPage: true });
  // Return through SPA navigation to prove the record was persisted, not just held in local state.
  await page.getByRole('link', { name: 'Settings', exact: true }).click();
  await page.getByRole('link', { name: 'SLA profiles', exact: true }).click();
  await page.getByLabel('Profile name', { exact: true }).fill(name);
  await page.getByRole('button', { name: 'Apply filters', exact: true }).click();
  await expect(page.getByRole('rowheader', { name, exact: true })).toBeVisible();
  await page.getByRole('link', { name, exact: true }).click();
  await expect(page.getByText('This profile has no saved versions.', { exact: true })).toBeVisible();
});

test('employee cannot navigate to the SLA configuration catalog', async ({ page }) => {
  await page.goto('/login');
  await page.getByLabel('Employee code', { exact: true }).fill('EMP001');
  await page.getByLabel('Password', { exact: true }).fill(process.env.BIZFLOW_E2E_PASSWORD!);
  await page.getByLabel('Workspace key', { exact: true }).fill(process.env.BIZFLOW_E2E_TENANT_KEY!);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('link', { name: 'Settings', exact: true }).click();
  await expect(page.getByRole('link', { name: 'SLA profiles', exact: true })).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'SLA configuration', exact: true })).toHaveCount(0);
});
