import { test, expect } from './fixtures';

test('administrator browses versions and creates a real empty workflow draft through Settings', async ({ page }, testInfo) => {
  await page.goto('/login');
  await page.getByLabel('Employee code', { exact: true }).fill('EMP001');
  await page.getByLabel('Password', { exact: true }).fill(process.env.BIZFLOW_E2E_PASSWORD!);
  await page.getByLabel('Workspace key', { exact: true }).fill(process.env.BIZFLOW_E2E_ADMIN_KEY!);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(/\/workspace$/);
  await page.getByRole('link', { name: 'Settings', exact: true }).click();
  await page.getByRole('link', { name: 'Workflows', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Workflows', exact: true })).toBeVisible();
  await page.getByLabel('Workflow name', { exact: true }).fill('Template workflow');
  await page.getByRole('button', { name: 'Apply filters', exact: true }).click();
  await expect(page.getByRole('navigation', { name: 'Workflow pages' })).toContainText('26 workflows');
  await expect(page.getByRole('rowheader', { name: /Reader workflow/ })).toHaveCount(0);
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await page.getByRole('link', { name: 'View version 1 of Template workflow 26', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Template workflow 26', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Fixture work step', exact: true })).toBeVisible();
  await expect(page.getByText('DRAFT → SUBMITTED', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Publish', exact: true })).toHaveCount(0);
  await page.getByRole('link', { name: 'Workflows', exact: true }).click();
  const name = `Access requests ${testInfo.project.name}`;
  await page.getByLabel('New workflow name', { exact: true }).fill(name);
  await page.getByRole('button', { name: 'Create draft', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Draft created' })).toBeVisible();
  await expect(page.getByRole('rowheader', { name: new RegExp(name) })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: testInfo.outputPath('workflow-library.png'), fullPage: true });
  await page.getByRole('link', { name: 'Open created draft', exact: true }).click();
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible();
  await expect(page.getByText('No steps have been configured.', { exact: true })).toBeVisible();
  await expect(page.getByText('No transitions have been configured.', { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('workflow-draft.png'), fullPage: true });
  const originalVersionUrl = page.url();
  await page.getByRole('button', { name: 'Create empty version', exact: true }).click();
  await expect(page.getByRole('status', { name: '' }).filter({ hasText: 'Draft version 2 created.' })).toBeVisible();
  await expect(page).toHaveURL(originalVersionUrl);
  await page.getByRole('link', { name: 'Open new draft', exact: true }).click();
  await expect(page).not.toHaveURL(originalVersionUrl);
  await expect(page.getByText(/Request · Version 2/)).toBeVisible();
  await expect(page.getByText('No steps have been configured.', { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('workflow-next-version.png'), fullPage: true });
  await page.goBack();
  await expect(page).toHaveURL(originalVersionUrl);
  await expect(page.getByText(/Request · Version 1/)).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Workflow version', exact: true })).toHaveCount(0);
  // Sessions are intentionally in-memory; a hard reload must not silently restore credentials.
  await expect(page).toHaveURL(/\/login$/);
});

test('employee sees only their workflow library and no draft-creation controls', async ({ page }) => {
  await page.goto('/login');
  await page.getByLabel('Employee code', { exact: true }).fill('EMP001');
  await page.getByLabel('Password', { exact: true }).fill(process.env.BIZFLOW_E2E_PASSWORD!);
  await page.getByLabel('Workspace key', { exact: true }).fill(process.env.BIZFLOW_E2E_TENANT_KEY!);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('link', { name: 'Settings', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Roles and permissions', exact: true })).toHaveCount(0);
  await page.getByRole('link', { name: 'Workflows', exact: true }).click();
  await expect(page.getByRole('rowheader', { name: /Reader workflow/ })).toBeVisible();
  await expect(page.getByRole('rowheader', { name: /Template workflow/ })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Create draft', exact: true })).toHaveCount(0);
  await page.getByRole('link', { name: 'View version 1 of Reader workflow', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Reader workflow', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Create empty version', exact: true })).toHaveCount(0);
});
