// <auto-generated />
using System;
using BizFlow.Domain.Audit;
using BizFlow.Domain.Organization;
using BizFlow.Domain.Security;
using BizFlow.Domain.Sla;
using BizFlow.Domain.Tenancy;
using BizFlow.Domain.Workflows;
using BizFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BizFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BizFlowDbContext))]
    [Migration("20261002182914_SlaSnapshotFoundation")]
    partial class SlaSnapshotFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "audit_actor_type", new[] { "AI_AGENT", "SYSTEM", "USER" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "company_status", new[] { "ACTIVE", "INACTIVE", "PENDING", "SUSPENDED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "permission_scope", new[] { "ASSIGNED", "DEPARTMENT", "PLATFORM", "SELF", "TENANT" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "record_status", new[] { "ACTIVE", "INACTIVE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "sla_profile_status", new[] { "ACTIVE", "DRAFT", "INACTIVE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tenant_status", new[] { "ACTIVE", "INACTIVE", "PROVISIONING", "SUSPENDED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_status", new[] { "ACTIVE", "INACTIVE", "LOCKED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "workflow_business_type", new[] { "REQUEST", "TASK" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "workflow_status", new[] { "ACTIVE", "DRAFT", "INACTIVE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "workflow_step_type", new[] { "ACTION", "APPROVAL", "CONFIRMATION" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "workflow_version_status", new[] { "DRAFT", "PUBLISHED", "RETIRED" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BizFlow.Domain.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AuditLogId");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<AuditActorType>("ActorType")
                        .HasColumnType("audit_actor_type");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ObjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ObjectType")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CreatedAt", "Id");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("BizFlow.Domain.Authentication.AuthenticationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AuthenticationSessionId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("FamilyId");

                    b.HasIndex("ReplacedById");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("AuthenticationSession", null, t =>
                        {
                            t.HasCheckConstraint("CK_AuthenticationSession_Expiry", "\"ExpiresAt\" > \"CreatedAt\"");

                            t.HasCheckConstraint("CK_AuthenticationSession_Hash", "\"TokenHash\" ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("CK_AuthenticationSession_Rotation", "\"ReplacedById\" IS NULL OR (\"RevokedAt\" IS NOT NULL AND \"ReplacedById\" <> \"AuthenticationSessionId\")");
                        });
                });

            modelBuilder.Entity("BizFlow.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("NotificationId");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<Guid?>("ObjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ObjectType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "RecipientId", "Id");

                    b.HasIndex("TenantId", "RecipientId", "ReadAt");

                    b.ToTable("Notification", null, t =>
                        {
                            t.HasCheckConstraint("CK_Notification_Text", "length(btrim(\"Title\")) > 0 AND length(btrim(\"Content\")) > 0 AND length(btrim(\"IdempotencyKey\")) > 0");

                            t.HasCheckConstraint("CK_Notification_Type", "\"Type\" IN ('TaskAssigned','TaskAccepted','TaskRejected','ProgressSubmitted','ResultSubmitted','TaskConfirmed','RequestSubmitted','RequestRouted','RequestReceived','RequestResolved','RequestRejected','RequestRevised','DeadlineWarning','Overdue','Escalation','ApprovalRequired')");
                        });
                });

            modelBuilder.Entity("BizFlow.Domain.Organization.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("DepartmentId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<RecordStatus>("Status")
                        .HasColumnType("record_status");

                    b.Property<Guid>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.HasIndex("TenantId", "ParentDepartmentId");

                    b.ToTable("Department", null, t =>
                        {
                            t.HasCheckConstraint("CK_Department_NoSelfParent", "\"ParentDepartmentId\" IS NULL OR \"ParentDepartmentId\" <> \"DepartmentId\"");
                        });
                });

            modelBuilder.Entity("BizFlow.Domain.Organization.ManagementScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ManagementScopeId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IncludeDescendants")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "DepartmentId");

                    b.HasIndex("TenantId", "UserId", "DepartmentId")
                        .IsUnique();

                    b.ToTable("ManagementScope", (string)null);
                });

            modelBuilder.Entity("BizFlow.Domain.Organization.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsPlatformAdministrator")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("NormalizedEmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<UserStatus>("Status")
                        .HasColumnType("user_status");

                    b.Property<Guid?>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "DepartmentId");

                    b.HasIndex("TenantId", "NormalizedEmail")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("TenantId", "NormalizedEmail"), false);

                    b.HasIndex("TenantId", "NormalizedEmployeeCode")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("TenantId", "NormalizedEmployeeCode"), false);

                    b.ToTable("User", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_AccessFailedCount", "\"AccessFailedCount\" >= 0");

                            t.HasCheckConstraint("CK_User_AccountPlane", "(\"TenantId\" IS NULL AND \"IsPlatformAdministrator\" AND \"DepartmentId\" IS NULL) OR (\"TenantId\" IS NOT NULL AND NOT \"IsPlatformAdministrator\")");
                        });
                });

            modelBuilder.Entity("BizFlow.Domain.Security.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("PermissionId");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<PermissionScope>("ScopeType")
                        .HasColumnType("permission_scope");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("BizFlow.Domain.Security.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("RoleId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<RecordStatus>("Status")
                        .HasColumnType("record_status");

                    b.Property<Guid?>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("TenantId", "Name"), false);

                    b.ToTable("Role", null, t =>
                        {
                            t.HasCheckConstraint("CK_Role_Scope", "(\"IsSystem\" AND \"TenantId\" IS NULL) OR (NOT \"IsSystem\" AND \"TenantId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("BizFlow.Domain.Security.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission", (string)null);
                });

            modelBuilder.Entity("BizFlow.Domain.Security.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("BizFlow.Domain.Sla.BusinessCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CalendarId");

                    b.Property<string>("HolidaysJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("WorkingHoursJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("BusinessCalendar", null, t =>
                        {
                            t.HasCheckConstraint("CK_BusinessCalendar_Holidays", "jsonb_typeof(\"HolidaysJson\") = 'array'");

                            t.HasCheckConstraint("CK_BusinessCalendar_Hours", "jsonb_typeof(\"WorkingHoursJson\") = 'object'");
                        });
                });

            modelBuilder.Entity("BizFlow.Domain.Sla.SlaProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("SLAProfileId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<SlaProfileStatus>("Status")
                        .HasColumnType("sla_profile_status");

                    b.Property<Guid>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Status", "Name");

                    b.ToTable("SLAProfile", null, t =>
                        {
                            t.HasCheckConstraint("CK_SLAProfile_Name", "length(btrim(\"Name\")) BETWEEN 1 AND 200");
                        });
                });

            modelBuilder.Entity("BizFlow.Domain.Sla.SlaVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("SLAVersionId");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid");

                    b.Property<string>("EscalationConfigJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SlaProfileId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("SLAProfileId");

                    b.Property<int>("TargetMinutes")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer");

                    b.Property<int>("WarningMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.HasIndex("SlaProfileId", "VersionNo")
                        .IsUnique();

                    b.ToTable("SLAVersion", null, t =>
                        {
                            t.HasCheckConstraint("CK_SLAVersion_Escalation", "\"EscalationConfigJson\" IS NULL OR jsonb_typeof(\"EscalationConfigJson\") = 'object'");

                            t.HasCheckConstraint("CK_SLAVersion_Number", "\"VersionNo\" > 0");

                            t.HasCheckConstraint("CK_SLAVersion_Thresholds", "\"TargetMinutes\" > 0 AND \"WarningMinutes\" >= 0 AND \"WarningMinutes\" < \"TargetMinutes\"");
                        });
                });

            modelBuilder.Entity("BizFlow.Domain.Tenancy.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CompanyId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<CompanyStatus>("Status")
                        .HasColumnType("company_status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("BizFlow.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TenantStatus>("Status")
                        .HasColumnType("tenant_status");

                    b.Property<string>("TenantKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.HasIndex("TenantKey")
                        .IsUnique();

                    b.ToTable("Tenant", (string)null);
                });

            modelBuilder.Entity("BizFlow.Domain.Tenancy.TenantSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TenantSettingId");

                    b.Property<string>("Key")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique();

                    b.ToTable("TenantSetting", null, t =>
                        {
                            t.HasCheckConstraint("CK_TenantSetting_Value", "bizflow_valid_tenant_setting(\"Key\", \"ValueJson\")");
                        });
                });

            modelBuilder.Entity("BizFlow.Domain.Workflows.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("WorkflowId");

                    b.Property<WorkflowBusinessType>("BusinessType")
                        .HasColumnType("workflow_business_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<WorkflowStatus>("Status")
                        .HasColumnType("workflow_status");

                    b.Property<Guid>("TenantId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Workflow", (string)null);
                });

            modelBuilder.Entity("BizFlow.Domain.Workflows.WorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("WorkflowStepId");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<string>("StepCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<WorkflowStepType>("Type")
                        .HasColumnType("workflow_step_type");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WorkflowVersionId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowVersionId", "OrderNo")
                        .IsUnique();

                    b.HasIndex("WorkflowVersionId", "StepCode")
                        .IsUnique();

                    b.ToTable("WorkflowStep", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkflowStep_Code", "\"StepCode\" ~ '^[A-Z0-9_.-]{1,80}$'");

                            t.HasCheckConstraint("CK_WorkflowStep_JsonObject", "jsonb_typeof(\"ConfigJson\") = 'object'");

                            t.HasCheckConstraint("CK_WorkflowStep_Order", "\"OrderNo\" > 0");
                        });
                });

            modelBuilder.Entity("BizFlow.Domain.Workflows.WorkflowTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TransitionId");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GuardJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WorkflowVersionId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowVersionId");

                    b.ToTable("WorkflowTransition", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkflowTransition_JsonObject", "\"GuardJson\" IS NULL OR jsonb_typeof(\"GuardJson\") = 'object'");
                        });
                });

            modelBuilder.Entity("BizFlow.Domain.Workflows.WorkflowVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("WorkflowVersionId");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<WorkflowVersionStatus>("Status")
                        .HasColumnType("workflow_version_status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "VersionNo")
                        .IsUnique();

                    b.ToTable("WorkflowVersion", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkflowVersion_JsonObject", "jsonb_typeof(\"DefinitionJson\") = 'object'");

                            t.HasCheckConstraint("CK_WorkflowVersion_Number", "\"VersionNo\" > 0");

                            t.HasCheckConstraint("CK_WorkflowVersion_Publication", "(\"Status\" = 'DRAFT' AND \"PublishedAt\" IS NULL) OR (\"Status\" <> 'DRAFT' AND \"PublishedAt\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("BizFlow.Domain.Audit.AuditLog", b =>
                {
                    b.HasOne("BizFlow.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BizFlow.Domain.Authentication.AuthenticationSession", b =>
                {
                    b.HasOne("BizFlow.Domain.Authentication.AuthenticationSession", null)
                        .WithMany()
                        .HasForeignKey("ReplacedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BizFlow.Domain.Organization.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BizFlow.Domain.Notifications.Notification", b =>
                {
                    b.HasOne("BizFlow.Domain.Organization.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BizFlow.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BizFlow.Domain.Organization.Department", b =>
                {
                    b.HasOne("BizFlow.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BizFlow.Domain.Organization.Department", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ParentDepartmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BizFlow.Domain.Organization.ManagementScope", b =>
                {
                    b.HasOne("BizFlow.Domain.Organization.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BizFlow.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BizFlow.Domain.Organization.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BizFlow.Domain.Organization.Department", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "DepartmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BizFlow.Domain.Organization.UserAccount", b =>
                {
                    b.HasOne("BizFlow.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BizFlow.Domain.Organization.Department", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "DepartmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BizFlow.Domain.Security.Role", b =>
                {
                    b.HasOne("BizFlow.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BizFlow.Domain.Security.RolePermission", b =>
                {
                    b.HasOne("BizFlow.Domain.Security.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BizFlow.Domain.Security.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BizFlow.Domain.Security.UserRole", b =>
                {
                    b.HasOne("BizFlow.Domain.Security.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BizFlow.Domain.Organization.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BizFlow.Domain.Sla.BusinessCalendar", b =>
                {
                    b.HasOne("BizFlow.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BizFlow.Domain.Sla.SlaProfile", b =>
                {
                    b.HasOne("BizFlow.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BizFlow.Domain.Sla.SlaVersion", b =>
                {
                    b.HasOne("BizFlow.Domain.Sla.BusinessCalendar", null)
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BizFlow.Domain.Sla.SlaProfile", null)
                        .WithMany()
                        .HasForeignKey("SlaProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BizFlow.Domain.Tenancy.Tenant", b =>
                {
                    b.HasOne("BizFlow.Domain.Tenancy.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BizFlow.Domain.Tenancy.TenantSetting", b =>
                {
                    b.HasOne("BizFlow.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BizFlow.Domain.Organization.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BizFlow.Domain.Workflows.WorkflowDefinition", b =>
                {
                    b.HasOne("BizFlow.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BizFlow.Domain.Workflows.WorkflowStep", b =>
                {
                    b.HasOne("BizFlow.Domain.Workflows.WorkflowVersion", null)
                        .WithMany()
                        .HasForeignKey("WorkflowVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BizFlow.Domain.Workflows.WorkflowTransition", b =>
                {
                    b.HasOne("BizFlow.Domain.Workflows.WorkflowVersion", null)
                        .WithMany()
                        .HasForeignKey("WorkflowVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BizFlow.Domain.Workflows.WorkflowVersion", b =>
                {
                    b.HasOne("BizFlow.Domain.Workflows.WorkflowDefinition", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
